language: elixir
elixir:
  - '1.7'

env:
  - MIX_TARGET=rpi3

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix archive.install hex nerves_bootstrap --force
  - mix deps.get --only test

script:
  - mix test
  - mix dialyzer
  - mix format --check-formatted

cache:
  directories:
    - priv/plts
