language: elixir
elixir:
  - '1.7'

env:
  - MIX_TARGET=rpi3

install:
  - mix local.hex --force
  - mix archive.install hex nerves_bootstrap --force
  - mix deps.get

jobs:
  include:
    - stage: test
      script: mix test
      env:
        - MIX_ENV=test
    - stage: dialyzer
      script: mix dialyzer
      env:
        - MIX_ENV=test
    - stage: format
      script: mix format --check-formatted
      env:
        - MIX_ENV=test

cache:
  directories:
    - priv/plts
