language: elixir
elixir:
  - '1.7'

env:
  - MIX_TARGET=rpi3

install:
  - LOCAL_ONLY=TRUE mix local.rebar --force
  - LOCAL_ONLY=TRUE mix local.hex --force
  - LOCAL_ONLY=TRUE mix archive.install hex nerves_bootstrap --force
  - mix deps.get

script:
  - mix test
  - mix dialyzer
  - mix format --check-formatted

cache:
  directories:
    - priv/plts
