language: elixir
elixir:
  - '1.4'

env:
  - MIX_TARGET=rpi3

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix archive.install hex nerves_bootstrap
  - mix deps.get --only test

script:
  - mix test
  - mix dialyzer
  - mix format --check-formatted

cache:
  directories:
    - priv/plts
